# Generated by Django 3.0.8 on 2020-07-16 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('introduction_text', models.CharField(max_length=200)),
                ('following_users', models.ManyToManyField(related_name='following', through='cms.Following', to='cms.User')),
            ],
        ),
        migrations.AddField(
            model_name='following',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='cms.User'),
        ),
        migrations.AddField(
            model_name='following',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='cms.User'),
        ),
    ]
