# Generated by Django 3.0.8 on 2020-07-16 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('introduction_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='Following',
            new_name='UserFollowing',
        ),
        migrations.CreateModel(
            name='PublicationWriter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication_writer', to='cms.Publication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer', to='cms.User')),
            ],
        ),
        migrations.CreateModel(
            name='PublicationEditor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication_editor', to='cms.Publication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editor', to='cms.User')),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='editors',
            field=models.ManyToManyField(related_name='editors', through='cms.PublicationEditor', to='cms.User'),
        ),
        migrations.AddField(
            model_name='publication',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.User'),
        ),
        migrations.AddField(
            model_name='publication',
            name='writers',
            field=models.ManyToManyField(related_name='writers', through='cms.PublicationWriter', to='cms.User'),
        ),
    ]
