# Generated by Django 3.0.8 on 2020-07-17 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20200716_1224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='introduction_text',
            new_name='introduction',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='introduction_text',
            new_name='introduction',
        ),
    ]
