# Generated by Django 3.0.8 on 2020-07-18 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20200717_1327'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserFollowing',
            new_name='FollowingUser',
        ),
    ]
