# Generated by Django 3.0.8 on 2020-07-18 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20200718_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='following_users',
            field=models.ManyToManyField(related_name='following_user', through='cms.FollowingUser', to='cms.User'),
        ),
        migrations.CreateModel(
            name='FollowingPublication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication', to='cms.Publication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='cms.User')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='following_publications',
            field=models.ManyToManyField(related_name='following_publication', through='cms.FollowingPublication', to='cms.Publication'),
        ),
    ]
