# Generated by Django 3.0.8 on 2020-07-19 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20200718_0742'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name='publicationwriter',
            name='publication',
        ),
        migrations.RemoveField(
            model_name='publicationwriter',
            name='user',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='editors',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='writers',
        ),
        migrations.DeleteModel(
            name='PublicationEditor',
        ),
        migrations.DeleteModel(
            name='PublicationWriter',
        ),
        migrations.AddField(
            model_name='publicationmember',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication_editor', to='cms.Publication'),
        ),
        migrations.AddField(
            model_name='publicationmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editor', to='cms.User'),
        ),
        migrations.AddField(
            model_name='publication',
            name='members',
            field=models.ManyToManyField(related_name='editors', through='cms.PublicationMember', to='cms.User'),
        ),
    ]
