# Generated by Django 3.0.8 on 2020-07-19 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_auto_20200719_0319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('content', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='followingpublication',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_publication', to='cms.Publication'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='members',
            field=models.ManyToManyField(related_name='members', through='cms.PublicationMember', to='cms.User'),
        ),
        migrations.AlterField(
            model_name='publicationmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='cms.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='following_publications',
            field=models.ManyToManyField(related_name='user_following_publication', through='cms.FollowingPublication', to='cms.Publication'),
        ),
        migrations.AlterField(
            model_name='user',
            name='following_users',
            field=models.ManyToManyField(related_name='user_following_user', through='cms.FollowingUser', to='cms.User'),
        ),
        migrations.CreateModel(
            name='StoryTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storytag_story', to='cms.Story')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_tag', to='cms.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='StoryPublication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_publication', to='cms.Publication')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storypublication_story', to='cms.Story')),
            ],
        ),
        migrations.AddField(
            model_name='story',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.User'),
        ),
        migrations.AddField(
            model_name='story',
            name='publication',
            field=models.ManyToManyField(related_name='publication', through='cms.StoryPublication', to='cms.Publication'),
        ),
        migrations.AddField(
            model_name='story',
            name='tag',
            field=models.ManyToManyField(related_name='tag', through='cms.StoryTag', to='cms.Tag'),
        ),
    ]
