# Generated by Django 3.0.8 on 2020-07-19 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_auto_20200719_0756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='publication',
        ),
        migrations.AddField(
            model_name='story',
            name='publication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='story_publication', to='cms.Publication'),
        ),
        migrations.DeleteModel(
            name='StoryPublication',
        ),
    ]
